# Generated by Django 3.0.4 on 2020-03-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=None, upload_to='images/book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='world',
            name='cover',
            field=models.ImageField(default=None, upload_to='images/world'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='image',
            field=models.ImageField(upload_to='images/chapter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to='images/user'),
        ),
    ]
